import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import styles from "../../styles/Nosotros.module.scss";
import data from "../../../data/presentation.json";
import Presentation from "@/components/Presentation/Presentation";

export const sobreNosotros = () => {
  return (
    <>
      <Head>
        <title>Navarro Rehabilitaciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Header />
      <main className={styles.mainContainer}>
        <img
          src="portadas/nosotros1.jpg"
          alt="Equipo Navarro Rehabilitación de Edificios"
          width="90%"
          className={styles.mainContainer__portrait}
        />
        <Presentation data={data.nosotros} />
      </main>
      <Footer />
    </>
  );
};

export default sobreNosotros;
