import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";

export const sobreNosotros = () => {
  return (
    <>
      <Head>
        <title>Navarro Rehabilitaciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1>SOBRE NOSOTROS</h1>
      </main>
      <Footer />
    </>
  );
};

export default sobreNosotros;
