import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import Presentation from "@/components/Presentation/Presentation";
import data from "../../../data/presentation.json";
import styles from "../../styles/Proyectos.module.scss";
import galleryData from "../../../data/projectsGallery";

export const proyectosRealizados = () => {
  return (
    <>
      <Head>
        <title>Navarro Rehabilitaciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <main className={styles.mainContainer}>
        <Presentation data={data.proyectos} />
        <section className={`${styles.projectsGallery}`}>
          {galleryData.map((img, index) => {
            return <img src={img.src} alt={img.alt} key={index} width="500" />;
          })}
        </section>
      </main>
      <Footer />
    </>
  );
};

export default proyectosRealizados;
