import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import Presentation from "@/components/Presentation/Presentation";
import data from "../../../data/presentation.json";

export const proyectosRealizados = () => {
  return (
    <>
      <Head>
        <title>Navarro Rehabilitaciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Presentation data={data.proyectos} />
      </main>
      <Footer />
    </>
  );
};

export default proyectosRealizados;
